language: python
python:
  - 2.6
  - 2.7
env:
  - DJANGO_VERSION=1.4.8
  - DJANGO_VERSION=1.5.4
install:
  - pip install Django==$DJANGO_VERSION
  - "pip install . --use-mirrors"
  - "pip install -r testproject/requirements.txt --use-mirrors"
  - "pip install -r testproject/requirements_test.txt --use-mirrors"
script:
  - cd testproject
  - python manage.py test fiber
  - coverage run --source=fiber manage.py test fiber
  - coverage report -m
after_success:
  - pip install -r requirements_coveralls.txt
  - coveralls
branches:
  only:
    - master
    - dev
    - coveralls
