language: python
python:
  - 2.7
  - 2.6
env:
  - DJANGO_VERSION=1.4.19
  - DJANGO_VERSION=1.5.12
  - DJANGO_VERSION=1.6.10
  - DJANGO_VERSION=1.7.4
matrix:
  exclude:
    - python: 2.6
      env: DJANGO_VERSION=1.7.4
install:
  - pip install Django==$DJANGO_VERSION
  - pip install -q -e .
  - pip install -q -r test-requirements.txt
script:
  - python testproject/manage.py test fiber_test
  - coverage run --source fiber --omit *migrations* testproject/manage.py test fiber_test
  - coverage report
after_success:
  - pip install coveralls
  - coveralls
branches:
  only:
    - master
    - dev
    - discover-runner
