language: python
python:
  - 2.6
install:
  - "pip install -r testproject/requirements.txt --use-mirrors"
script:
  - cd testproject
  - python manage.py jenkins
branches:
  only:
    - master
    - dev
